name: autozoom
description: "AutoZoom - Intelligent Class Calendar Sync & Instant Zoom Launcher"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  device_calendar: ^4.3.3
  flutter_local_notifications: ^17.2.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  timezone: ^0.9.4
  intl: ^0.19.0
  flutter_timezone: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
